name: Run All Scripts Sequentially
on:
  schedule:
    - cron: '*/45 * * * *'  # Setiap 45 menit
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      # === SETUP AWAL ===
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 transformers torch nltk pytz

      # === CACHE UNTUK HISTORY POSTED ARTICLES ===
      - name: Cache History bola.py
        uses: actions/cache@v3
        id: cache-bola
        with:
          path: posted_articles_bola.json
          key: ${{ runner.os }}-bola-${{ hashFiles('posted_articles_bola.json') }}

      - name: Cache History hot.py
        uses: actions/cache@v3
        id: cache-hot
        with:
          path: posted_articles_hot.json
          key: ${{ runner.os }}-hot-${{ hashFiles('posted_articles_hot.json') }}

      - name: Cache History biz.py
        uses: actions/cache@v3
        id: cache-biz
        with:
          path: posted_articles_biz.json
          key: ${{ runner.os }}-biz-${{ hashFiles('posted_articles_biz.json') }}

      # === RUN SCRIPTS BERGANTIAN ===
      - name: Run bola.py (Sepak Bola)
        env:
          FB_PAGE1_ID: ${{ secrets.FB_BOLA_PAGE1_ID }}
          FB_PAGE1_TOKEN: ${{ secrets.FB_BOLA_PAGE1_TOKEN }}
          FB_PAGE2_ID: ${{ secrets.FB_BOLA_PAGE2_ID }}
          FB_PAGE2_TOKEN: ${{ secrets.FB_BOLA_PAGE2_TOKEN }}
        run: |
          python bola.py
          # Ganti nama file JSON untuk menghindari konflik
          mv posted_articles.json posted_articles_bola.json

      - name: Run hot.py (Berita Hot)
        env:
          FB_PAGE1_ID: ${{ secrets.FB_HOT_PAGE1_ID }}
          FB_PAGE1_TOKEN: ${{ secrets.FB_HOT_PAGE1_TOKEN }}
          FB_PAGE2_ID: ${{ secrets.FB_HOT_PAGE2_ID }}
          FB_PAGE2_TOKEN: ${{ secrets.FB_HOT_PAGE2_TOKEN }}
        run: |
          python hot.py
          mv posted_articles.json posted_articles_hot.json

      - name: Run biz.py (Bisnis)
        env:
          FB_PAGE1_ID: ${{ secrets.FB_BIZ_PAGE1_ID }}
          FB_PAGE1_TOKEN: ${{ secrets.FB_BIZ_PAGE1_TOKEN }}
          FB_PAGE2_ID: ${{ secrets.FB_BIZ_PAGE2_ID }}
          FB_PAGE2_TOKEN: ${{ secrets.FB_BIZ_PAGE2_TOKEN }}
          FB_PAGE3_ID: ${{ secrets.FB_BIZ_PAGE3_ID }}
          FB_PAGE3_TOKEN: ${{ secrets.FB_BIZ_PAGE3_TOKEN }}
        run: |
          python biz.py
          mv posted_articles.json posted_articles_biz.json

      # === COMMIT PERUBAHAN HISTORY ===
      - name: Commit Changes
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add posted_articles_*.json
          git commit -m "Update history [skip ci]" || echo "No changes"
          git push
